version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo server --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/app
volumes:
  app:
